apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bnljk0maq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bnljk0maq-go 
  name: bnljk0maq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bnljk0maq-go 
